### ISSUE TITLE
Makefile.PL incorrectly refers to Date::Tolkien::Shire

### ISSUE THREAD

**Issue by Keith-S-Thompson** [trwyant/perl-DateTime-Calendar-Julian#1]
`Makefile.PL` lines 52-53 incorrectly refers to the repo for `Date::Tolkien::Shire`.

This causes the "Repository" information on the metacpan page to be incorrect:

https://metacpan.org/pod/DateTime::Calendar::Julian

**Comment by trwyant** [comment]
Thank you for finding and reporting this. It turns out DateTime-Calendar-Christian has the same problem. I will credit you with finding both.

Ah, the dangers of cut-and-paste.

A development release which (hopefully) fixes this just went to PAUSE.

**Comment by trwyant** [comment]
The production release has been out for a week and I have verified the Meta::CPAN metadata, so I am going to close this issue. Thank you again for letting me know about this.
